### ISSUE TITLE
Move to Web App - Remove Electron.js

### ISSUE THREAD

**Issue by AndreasDemenagas** [sufst/wireless-telemetry-gui#12]
### Description of Issue 

It has been mentioned - proposed that now, since now we are using a plain WebSocket to connect to the back-end and bring in data from the server, we should move the front-end GUI to a web app and get rid of the `Electron.js` dependency all together. 

### Current Methodology 

The current implementation of the front-end GUI uses a combination of web enabled technologies to produce a native desktop app. This allows us to produce executables that can be executed on any OS (mainly focusing on Windows and macOS but Linux can also work). The framework allowing this is `Electron.js` 

Behind the Electron wrapped, the actual codebase of the app is all written in `React.js`, using JavaScript and HTML - CSS (or what is known in React as JSX) 

### Proposal 

Removing the Electron bit of the application and have the app run as a designated web app. This can then be externally hosted on a `sufst.co.uk` subdomain - any other web domain - or even simpler served from `localhost` using a specified port like `localhost:3000`. 

This would bring a number of possible advantages for the front-end which I will try and mention here. 

- Multiple clients over the network. During competitions - or even testing if internet connections allow - everyone interested in the live telemetry could just open a web browser and load the GUI. This needs a form of a local network hotspot if the GUI is served over `localhost` but can should be able to be achieved. 

- Multiple routes. Having the GUI served as a web app would allow us to specify different routes for different sets of sensors. For example, something like `localhost:3000/aero` could display only aero sensors for use by the aero team etc...

Any other advantages will be noted in this issue. If anyone has any other thoughts / ideas feel free to mention them.

**Comment by AndreasDemenagas** [comment]
@Nathanrs97 Just mentioning you so you get notified

**Comment by Nathanrs97** [comment]
@AndreasDemenagas I'm very curious about this and want to have a play with it too... are you still going to use React.js like mentioned in the readme?

**Comment by AndreasDemenagas** [comment]
> I'm very curious about this and want to have a play with it too... are you still going to use React.js like mentioned in the readme? 

Yes, React is will still be used. I'll try and explain it a bit better. 

Currently, we are using React.js for all the components, UI rendering and state updates. React is most of the times used to create web applications, however there are frameworks out there - Electron in our case - that allow to take the existing JavaScript front-end code (like the React code) and turn it into an app that doesn't work on the web but instead works as a native web app. 

So, moving the GUI to a web app it is really straight forward. We just remove the Electron bit and use React on the web - as it is designed to be used haha.

**Comment by Nathanrs97** [comment]
Damn sounds interesting. I'm getting into web technologies quite a bit recently so I'll have a play and perhaps can contribute to the  GUI if my code is any good haha. 

What IDE are you using? I see on the wiki how to run the GUI but not really the development workflow (do you use like Visual Studio?)

**Comment by AndreasDemenagas** [comment]
> so I'll have a play and perhaps can contribute to the GUI if my code is any good haha.

Any contributions will be more than welcome 😛

> What IDE are you using?

I am current using Visual Studio Code - it's like Visual Studio but without the IDE part and since JS is not a compiled language it allows for a more lightweight editor.

**Comment by Nathanrs97** [comment]
Just loaded up Visual Studio and creating a Node.js project there is an option for a web application. Selecting it loads a project where it seems to use node.js as a server to serve the webpages to a client e.g. localhost:1337 (from my basic understanding haha).

I'm going to have a play over the next week or so on it and see what I can learn and get working haha. Then probably if you or someone has time to look at it and see if I'm any good at JS.

**Comment by AndreasDemenagas** [comment]
Nice nice. I would recommend starting with some React.js tutorials since this is the biggest thing that we are using on the front-end and its way of doing things is quite different that anything from vanilla JavaScript HTML and CSS. 

Traversy Media on YouTube is where I have learned all my React skills from 😂 so I recommend. If you have any questions feel free to ask - although I myself have only got into React in the last year or so. 

Also, if you have a discord account and you want to join our GUI project server where we discuss almost everything, feel free to reply with your discord username 🙂

**Comment by Nathanrs97** [comment]
Sil#5735
