### ISSUE TITLE
Get @ import working

### ISSUE THREAD

**Issue by Nathanrs97** [sufst/wireless-telemetry-gui#17]
The current import paths of `../../` is dumb.

https://stackoverflow.com/questions/42711175/what-does-the-symbol-do-in-javascript-imports

**Comment by AndreasDemenagas** [comment]
Quick 24second YouTube video [video](https://youtu.be/WpgZKBtW_t8) that explains this topic. 

Will need to add a `jsconfig.json` file - although this might be possible in the classic `package.json`.

**Comment by AndreasDemenagas** [comment]
https://github.com/facebook/create-react-app/issues/5645#
https://github.com/storybookjs/storybook/issues/7205
