### ISSUE TITLE
feat(sessions): View Sessions Page

### ISSUE THREAD

**Issue by AndreasDemenagas** [sufst/wireless-telemetry-gui#21]
### Route 
* `/sessions`

Implement a system where all logged in users will be able to view past sessions from the back-end - download their CSV files - as well as view details about them. 
Possible details include: 
* Date
* Sensors Running
* Car 
* Driver Name
* Location 
* Competition or Testing
* etc...

These should be available from the backend server

**Comment by Grvs44** [comment]
There are quite a few different available sensors in the data for the single session, too many to make it sensible to create multiple CSV files (this would be possible but would be inconvenient for the user). Should a different format such as JSON be used, or display the data in the browser?
