### ISSUE TITLE
Update Dashboard Session Tab

### ISSUE THREAD

**Issue by Nathanrs97** [sufst/wireless-telemetry-gui#22]
The dash's session tab needs finishing with the following features:
 - Session name (which updates based on the current active session from the front-end).
 - Start/stop session.
 - New session menu to create a new session (needs session name and sensors to capture inputs, along with a submit button).
 - Information area that displays the current session capturing sensors, all active sessions, and possible meta-information about the active session (e.g. captured data points up (needs back-end support)).

**Comment by tvasuthevan123** [comment]
To Do List
- [x] Look through back-end code to see supported request to the server
- [x] Look through front-end code to see where to add session creation
- [x] Add session creation
  - [x] Start/Stop button
  - [x] New session 
  - [x] Info
    - [ ] Component
    - [ ] Displaying info

**Comment by tvasuthevan123** [comment]
- [ ] Remove submit button when session started#
- [ ] Switch state of start button when started

**Comment by tvasuthevan123** [comment]
- [ ] List of active sessions with stop button
- [ ] List of inactive sessions with download button
