### ISSUE TITLE
Revising the front-end protocol

### ISSUE THREAD

**Issue by Nathanrs97** [sufst/wireless-telemetry-gui#3]
Thought raising this here would be more likely to be noticed by you guys on the front-end GUI.

I've been taking a look at the code and seems like decoding the JSON payloads look quite messy. So I thought I would raise an issue so we could discuss revising it to make it easier for you guys (especially with me currently updating the server to use a database so staging the data before it gets to the front-end is easier and more flexible).

- A RESTful implementation over the TCP socket so the front-end could make sensor data requests e.g. "GET /sensors/RPM?time=10" would return a JSON of the last 10 seconds of RPM data, or "GET /sensors?time=10" would return all sensor data over the last 10 seconds.
- The JSON format is for each sensor is just `<sensor_name>: [ {<time>, <value>}, ... ]` (name is e.g. RPM and TPS rather than the current numbers).
- No change.

Thoughts? I think the RESTful implementation would be good as we could expand it with different types of requests so you can request all sorts of backend data when you want (or when a user wants), rather than just getting a constant feed of everything all the time.

**Comment by Nathanrs97** [comment]
@AndreasDemenagas @maxobrien

**Comment by Nathanrs97** [comment]
Thought about the RESTful API some more and most likely the best way (if you guys like the idea) is to have at the bare minimal `"GET /sensors?timesince=<time>"` so then you guys could request all sensor data every e.g. 0.5 seconds and it will return all sensor data since the timestamp given in <time> (so the last 0.5 seconds worth here).

**Comment by AndreasDemenagas** [comment]
> * A RESTful implementation over the TCP socket so the front-end could make sensor data requests e.g. "GET /sensors/RPM?time=10" would return a JSON of the last 10 seconds of RPM data, or "GET /sensors?time=10" would return all sensor data over the last 10 seconds
> * The JSON format is for each sensor is just `<sensor_name>: [ {<time>, <value>}, ... ]` (name is e.g. RPM and TPS rather than the current numbers).
> * No change.

@Nathanrs97  So current all the decoding & parsing (which I just finished today 😂) is handled in `parser.js` and with what is definitely the least efficient way to do it. 

> RESTful API some more and most likely the best way (if you guys like the idea) is to have at the bare minimal "GET /sensors?timesince=<time>"

Personally speaking, I think this would be the best way to move ahead. It fixes pretty much all of the workarounds that I had to do in the parsing - while also addressing the issue with the current implementation that the UI handles a lot of the data manipulation, which should ideally be handled by the server

**Comment by AndreasDemenagas** [comment]
There are also another couple of ideas I have for this approach so I will list them here just for future development reference. 

1. Have the amount of data returned by the RESTful service limited by the number of points a graph can handle. If you see on the parser.js, in order to only graph the last x amount of points and not all of them from the beginning, I am limiting the parsing to arrays that hold only the x last values - now set to 20 for testing purposes. 

What I really mean here is that for example, if graphs can only hold 20 values, have `GET /sensors?timesince=<time>` return the last 20 values instead of all the values (since we can only graph 20)

2. Have an endpoint like `/sensors/RPM?limit=0` or similar that returns all the broadcasted data for that sensor. That would be really really helpful for us since we are currently using a super-hacky code to turn the data into the appropriate format CSV exports. (And I also think the export is now broken due to parsing being limited)

**Comment by Nathanrs97** [comment]
> @Nathanrs97 So current all the decoding & parsing (which I just finished today 😂) is handled in parser.js and with what is definitely the least efficient way to do it. 

Ouch! I'm sorry I didn't bring this forward (only started working on the server again today). I hope at least through working with the current approach you're much more aware of improvements we can make (which it seems is so).

> which should ideally be handled by the server

I agree. As it seems now we agree to go the RESTful route, I will let you decide the API (so then the server can produce whatever format you require to make the front-end as efficient as possible and allows you to spend less time on data manipulation and more time on making great features 😄.

> Have the amount of data returned by the RESTful service limited by the number of points a graph can handle

This can be done with another argument e.g. `GET /sensors/RPM?amount=50` would return up to 50 data entry points in the response (even if there was more then these will be ignored). We can also stack them so this would be valid e.g. `GET \sensors\RPM?time=10&amount=50`. 

I think the best way forward is perhaps if you could create an issue or wiki or similar on this repo detailing the RESTful API wanted and then I can work backwards and implement it in the server. To get us started I have so far:

- `GET \sensors?timesince=<n>&amount=<i>` (Same for specific sensors e.g. `\sensors\RPM`)

**Comment by Nathanrs97** [comment]
> I think the best way forward is perhaps if you could create an issue or wiki or similar on this repo detailing the RESTful API wanted and then I can work backwards and implement it in the server.

Go nuts with the API (even if you decide you want something like `GET \sensors?time=<n>&amount=<i>&timeformat=<format>&dataformat=<format>...`.

**Comment by AndreasDemenagas** [comment]
> This can be done with another argument e.g. GET /sensors/RPM?amount=50 would return up to 50 data entry points in the response (even if there was more then these will be ignored)

Yes that would be perfect! 

Another thing, (because we have established I am new to TCP networking 😂) - this RESTful approach will be like browser networking right? So, I just hit a GET request to `localhost:<port>/sensors/RPM` and it will return back a JSON object

[clicked the close btn by mistake - sorry]

**Comment by AndreasDemenagas** [comment]
> Go nuts with the API (even if you decide you want something like `GET \sensors?time=<n>&amount=<i>&timeformat=<format>&dataformat=<format>...`.

**Comment by Nathanrs97** [comment]
> Another thing, (because we have established I am new to TCP networking 😂) - this RESTful approach will be like browser networking right? So, I just hit a GET request to localhost:<port>/sensors/RPM and it will return back a JSON object

You would just need to write the string e.g. `"GET \sensors?time=10"` on the socket object you opened to the server (Not familiar with javascript but I imagine it would be like `TCP.send("GET \sensors?time=10")` then at some point in the future you do like `TCP.recv()`?

**Comment by Nathanrs97** [comment]
Looking at the code I see here in the App.js
```
const client = new net.Socket();
	
client.connect({ port: PORT, host: HOST }, () => {
	client.write(AIPDU, ()  => {
		// Successfully Connected to Back-End Server
		this.setState({ connection_status: 'CONNECTED'} )
	})
})

client.on('data',  (data) => {
	// Called everytime data has been received by the back-end
	const oldData = this.state.data
	const newData = JSON.parse(data); 
	const parsedData = parseData(oldData, newData);

	switch (parsedData.type) {
		case 2:
			this.onReceivedCore(parsedData);
			break;
		default:
			break;
	}
})
```

You could put the request strings you want to send when you do `client.write`. Then at some point in the future the `client.on` will receive the response.

**Comment by Nathanrs97** [comment]
I can make the RESTful API sit on a WebSocket if you would prefer (if you have more experience with WebSockets in javascript)?

**Comment by AndreasDemenagas** [comment]
To be completely honest I have not much experience with neither 😂. Personally I would quite prefer the WebSocket route since it bundles so well with the web technologies (Electron - React - JS) we use and I know there are much more sources out there to figure out what I am doing. 

However, again, since I have not much experience with neither of them, if you prefer - and are comfortable - doing it with the classic TCP Socket method feel free to do so! I will have to do quite some learning regardless the approach you go.

**Comment by Nathanrs97** [comment]
>  Personally I would quite prefer the WebSocket route since it bundles so well with the web technologies (Electron - React - JS)

I agree. Since we are bundling the data up into chunks and requesting only every few hundred 100ms or so there should not be a performance impact using WebSockets. 

Until we can finalise the RESTful API, assume you'll have access to at least 
- `GET \sensors?timesince=<epoch>&points=<n>` where `<epoch>` is in `float` form [some info here on using this in javascript](https://www.epoch101.com/Javascript) and `<n>` is the maximum number of data points returned in the JSON.
- The JSON (comment if you want someone different) returned will be in the form:
```
{
	<sensor_name>: [ {
	"epoch": <float>,
	"value": <depends on the sensor but will be either int, float, or bool>
	} ], [ { ... } ],
	...
}
```

**Comment by AndreasDemenagas** [comment]
Yes performance-wise the WebSocket looks like it will be good as well. 

For the JSON you have sent, I don't quite understand why the `<sensor_name>` object has a number of `[...]` objects inside it. You have the sensor object holding many arrays of one element each

Did you mean the `sensor_name` object to hold an array of objects with `epoch` and `value`?

I think something like this would make more sense: 

```
name: {
  [
    {
      epoch: <number>,
      value: <int> or <bool>
    },
    {
      epoch: <number>,
      value: <int> or <bool>
    },
    {
      epoch: <number>,
      value: <int> or <bool>
    }
    ...
  ]
}
```

**Comment by Nathanrs97** [comment]
Yeah, this is what I meant haha I edited my comment a few times to try and make it clearer. So an example would be (with `GET \sensors?` is requested so multiple sensors data are returned):
```
{
	RPM:
	[
		{
		epoch: 1,
		value: 11
		},
		{
		epoch: 2,
		value: 12
		},
		{
		epoch: 3,
		value: 13
		}
	],
	TPS:
	[
		{
		epoch: 1,
		value: 11
		},
		{
		epoch: 2,
		value: 12
		},
		{
		epoch: 3,
		value: 13
		}
	]
}
```

So here you can see that the RPM entry with epoch `1` is the same time as TPS entry with epoch `1`.

**Comment by AndreasDemenagas** [comment]
This looks all good. I will look more into this tomorrow because it's getting almost 2am here 😂. 

The "perfect" format of the JSON really depends on the graphing library we use though. That's because some libs require just an array passed into them so they can graph it - while others require an object like you have here with a "time" and a "value" field. 

Either way we can obviously adjust the format later in the front end depending on the requirements of the graphing library

**Comment by Nathanrs97** [comment]
> Either way we can obviously adjust the format later in the front end depending on the requirements of the graphing library

Something to think about once you know the format that is required. We can have something like `GET \sensors?format=<type>` which formats the JSON in a specific way that makes it easier for you to use. Until then we'll work with the above format.

**Comment by Nathanrs97** [comment]
Closing this ticket as agreement on the revision to the front-end Protocol (RESTful) has been established and implemented in the intermediate server.
