### ISSUE TITLE
feat(admin): update user information

### ISSUE THREAD

**Issue by AndreasDemenagas** [sufst/wireless-telemetry-gui#46]
### Description
Use a button on the users table present in `/admin` to update the information about a user in the server. 

### Requirements
- [ ] Add a UI button element to the table for each row. 
- [ ] Present existing user information by fetching that if required 
- [ ] Design a UI to allow users to enter new details. 
- [ ] Use the appropriate API call from `/api` to update the user information to the server.
- [ ] Update the row on the table with the new information

**Comment by awaisnasir9** [comment]
Me and Sam will take this!
