### ISSUE TITLE
Export Data as CSV

### ISSUE THREAD

**Issue by AndreasDemenagas** [sufst/wireless-telemetry-gui#8]
Data from the server should be able to be exported to a CSV format from within the application. This makes all data decisions and analysis easier to analyze and also acts like a secure backup for the built-in SD card on the car. 

This could be implemented in 2 ways. 
* Store all the sensor data as they are retrieved from the server, using a CSV friendly format. 

* Request all the data of a specific sensor from the server when the user hits the export CSV button. 

@Nathanrs97 Does the current RESTful approach include an endpoint for retrieving **all** the data logged for a specific sensor without any number limits or epoch times?

**Comment by AndreasDemenagas** [comment]
Note that this feature is implemented for the previous server implementation but needs to be completely revamped for the RESTful approach.

**Comment by Nathanrs97** [comment]
We can implement a filter like `GET /sensors?timebetween=[<time>, <time>]` which will return all sensor data between those two epoch times. This may be a lot of data but should be fine over WebSocket with a good connection (on `localhost` it shouldn't have any issue).

This might be good as then the front-end could allow the user to export a .csv even from old data (especially if we go the route of storing a copy of the server database on a cloud server like Amazon for permanent storage).

**Comment by AndreasDemenagas** [comment]
This sound good! I will raise all these issues tomorrow on the team's weekly meeting and make sure to comment anything that might come up.

**Comment by AndreasDemenagas** [comment]
Closing for now - been included in #21
