### ISSUE TITLE
bug: session List Not Updated Immediately

### ISSUE THREAD

**Issue by tvasuthevan123** [sufst/wireless-telemetry-gui#80]
### Description
When starting/stopping sessions, unless you refresh the page, the list of sessions does not get updated.

### Steps To Reproduce
1. Start a session
2. Check the list of sessions

### Environment
Operating system, toolchain, etc.

### Expected Behaviour
Update list upon session interaction.

### Relevant FSUK Rules
**EV?.??.?** ...

### Additional Notes
Any additional notes.

**Comment by Grvs44** [comment]
Implemented in #90
